# Use Python as the base image
FROM python:3.10

# Set the working directory
WORKDIR /app

# Copy the project files
COPY . .

# Install dependencies
RUN pip install -r requirements.txt

# Run the Saleor API
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
